version: "3.7"

secrets:
  cert:
    file: ./certs/chain.pem
  pkey:
    file: ./certs/pkey.pem

services:
  db-explorer:
    image: mongo-express
    ports:
      - 4001:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
  db:
    image: mongo:3
  backend:
    image: node:12-alpine
    command: npm run dev
    working_dir: /app
    user: "1000"
    secrets:
      - pkey
      - cert
    environment:
      - APP_ADDR=0.0.0.0
      - APP_PORT=4000
      - MONGO_URI=mongodb://db/db0
      - MONGO_URI_TEST=mongodb://db/db0_test
      - APP_TLS_PORT=4443
      - APP_TLS=1
    ports:
      - 4000:4000
      - 4443:4443
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /home:/home
      - ${PWD}/backend:/app
  frontend:
    image: node:12-alpine
    command: npm run serve
    working_dir: /app
    user: "1000"
    environment:
      - HOST=0.0.0.0
      - PORT=4002
    ports:
      - 4002:4002
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /home:/home
      - ${PWD}/frontend:/app
